# server
server:
  port: 8082
  servlet:
    context-path: /ssj

# spring
spring:
  application:
    name: ssj
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssj
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  redis:
    port: 6379
    host: 192.168.0.110

# log
logging:
  level:
    org.example: trace

# mybatis
mybatis:
  mapper-locations: mapper/*
  configuration:
    map-underscore-to-camel-case: true